FROM ruby:3.2
LABEL maintainer="Palve <palvefs@gmail.com>"

RUN mkdir /data
WORKDIR /data

RUN \
    apt-get update && \
    apt-get install --no-install-recommends -y locales && \
    apt-get clean

COPY Gemfile Gemfile.lock /data/

RUN \
    gem install bundler -v "$(sed --silent -r '/BUNDLED WITH/,+1 {s/^[\t ]+//; p}' Gemfile.lock | tail -n +2)" && \
    bundle install --frozen

ENV LANG en_US.UTF-8
ENV JEKYLL_ENV production

COPY . /data

CMD ["bundle", "exec", "jekyll", "build"]