FROM ruby:3.2
LABEL maintainer="Palve <palvefs@gmail.com>"

RUN mkdir /data
WORKDIR /data

RUN \
    apt-get update && \
    apt-get install --no-install-recommends -y locales && \
    apt-get clean
RUN curl -fsSL "https://cdn.jsdelivr.net/gh/tj/n/bin/n" | bash -s -- lts

COPY Gemfile Gemfile.lock package.json package-lock.json* /data/

RUN \
    gem install bundler -v "$(sed --silent -r '/BUNDLED WITH/,+1 {s/^[\t ]+//; p}' Gemfile.lock | tail -n +2)" && \
    bundle config set --local frozen false && \
    bundle config set --local deployment false && \
    bundle install && \
    NODE_ENV=production npm install --no-audit --no-fund && \
    mv node_modules ../ && \
    rm -rf /data/*

ENV LANG=C.UTF-8
ENV JEKYLL_ENV=production

CMD ["sh", "-c", "bundle exec jekyll build && node build-js.mjs"]

