FROM ruby:3.2

RUN mkdir /data
WORKDIR /data

RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

COPY Gemfile Gemfile.lock ./

RUN gem install bundler && bundle install

RUN if [ -f /usr/local/bundle/gems/babel-transpiler-0.7.0/lib/babel/transpiler.rb ]; then \
  sed -i 's/@context ||= ExecJS.compile("var self = this; " + File.read(script_path))/@context ||= ExecJS.compile("var self = this; " + File.read(script_path, :encoding => "UTF-8"))/' /usr/local/bundle/gems/babel-transpiler-0.7.0/lib/babel/transpiler.rb; \
  fi

ENV LANG en_US.UTF-8

COPY . .

CMD ["jekyll", "build"]
