map $http_user_agent $isbrowser {
        default 0;
        "~*validation server" 0;
        "~*mozilla" 1;
}

server{
        # HTTP/HTTPS settings
        listen 80;
        listen [::]:80;
        server_name 127.0.0.1;
        # fancyindex settings
        fancyindex_header /fancy-index/before;
        fancyindex_footer /fancy-index/after;
        fancyindex_exact_size off;
        fancyindex_time_format "%d %b %Y %H:%M:%S +0000";
        fancyindex_ignore fancyindex;

        error_page 404 /404.html;

        # fancy
        location /fancy-index {
                internal;
                root /workspaces/ha-mirrors-web/_site;
                subrequest_output_buffer_size 100k;
                location = /fancy-index/before {
                        js_content fancyIndexRender.fancyIndexBeforeRender;
                }
                location = /fancy-index/after {
                        js_content fancyIndexRender.fancyIndexAfterRender;
                }
        }

        # njs settings
        js_path /workspaces/ha-mirrors-web/_site/static/njs;
        js_import fancyIndexRender from /workspaces/ha-mirrors-web/_site/static/njs/fancy_index.njs;

        location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
        {
                return 404;
        }

        location @close413 {
                return 444;
        }

        #web 页面
        location / {
                root /workspaces/ha-mirrors-web/_site;
                try_files $uri $uri/ @handle404;
                fancyindex on;
                error_page 413 = @close413;

        }
        location @handle404 {
                if (-f $request_filename) {
                        return 301 $scheme://$host$request_uri/;
                }
                return 404;
        }
}